<script setup>
import { ref } from "vue";
import { Download, Plus, RotateCcw, Upload, FileJson, Users, FileText, Share2 } from "lucide-vue-next";
import { useCaseStore } from "./stores/useCaseStore";
import SuspectCard from "./components/SuspectCard.vue";
import ClueTimeline from "./components/ClueTimeline.vue";
import RelationGraph from "./components/RelationGraph.vue";
import BaseButton from "./components/ui/BaseButton.vue";

const store = useCaseStore();

const triggerDownload = (content, filename, type) => {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
};

const exportData = () => {
  let content = `# ${store.scriptTitle}\n\n`;
  content += `>Generated by Ariadne Clue Organizer\n\n`;

  content += `## 👥 嫌疑人名单\n`;
  store.suspects.forEach((s) => {
    content += `- **${s.name}** ${s.isKiller ? "(🔴凶手)" : ""}: ${
      s.note || "暂无备注"
    }\n`;
  });

  content += `\n## 🕵️‍♂️ 线索流\n`;
  store.clues.forEach((c) => {
    const links = c.linkedSuspectIds
      .map((id) => store.suspects.find((s) => s.id === id)?.name)
      .filter(Boolean)
      .join(", ");
    content += `### ${c.time}\n`;
    content += `- ${c.content}\n`;
    if (links) content += `- 关联: ${links}\n`;
    content += `\n`;
  });

  triggerDownload(content, `${store.scriptTitle || "case"}_report.md`, "text/markdown");
};

const exportJSON = () => {
    const json = store.exportState()
    triggerDownload(json, `${store.scriptTitle || "case"}_data.json`, "application/json")
}

const importJSON = () => {
    const input = document.createElement('input')
    input.type = 'file'
    input.accept = 'application/json'
    input.onchange = (e) => {
        const file = e.target.files[0]
        if (!file) return
        
        const reader = new FileReader()
        reader.onload = (e) => {
            const success = store.importState(e.target.result)
            if(success) alert('剧本数据导入成功！')
        }
        reader.readAsText(file)
    }
    input.click()
}

// Lightbox
const previewImage = ref(null)
const handlePreviewImage = (src) => {
    previewImage.value = src
}

// Mobile Tabs
const activeTab = ref('timeline') // 'suspects', 'timeline', 'graph'
</script>

<template>
  <div class="min-h-screen bg-black/40 backdrop-blur-3xl flex flex-col">
    <!-- Background Texture -->
    <div
      class="fixed inset-0 pointer-events-none opacity-5 bg-[url('https://www.transparenttextures.com/patterns/dark-matter.png')]"
    ></div>

    <!-- Header -->
    <header
      class="h-16 border-b border-mystery-800 flex items-center justify-between px-6 bg-mystery-900/80 backdrop-blur z-20"
    >
      <div class="flex items-center gap-4">
        <h1 class="text-mystery-gold font-serif text-2xl tracking-wider">
          ARIADNE
        </h1>
        <div class="h-6 w-px bg-mystery-700 mx-2"></div>
        <input
          v-model="store.scriptTitle"
          class="bg-transparent text-xl font-bold text-slate-200 focus:outline-none placeholder-slate-600 font-serif w-64 md:w-96"
          placeholder="在此输入剧本名称..."
        />
      </div>
      <div class="flex items-center gap-3">
        <BaseButton @click="store.resetCase" variant="ghost" class="text-xs" title="清空所有数据">
          <RotateCcw class="w-4 h-4" />
        </BaseButton>
        <div class="h-6 w-px bg-mystery-700 mx-1"></div>
        
        <BaseButton @click="importJSON" variant="secondary" title="导入数据">
            <Upload class="w-4 h-4" />
        </BaseButton>
        <BaseButton @click="exportJSON" variant="secondary" title="备份数据 (JSON)">
            <FileJson class="w-4 h-4" />
        </BaseButton>
        <BaseButton @click="exportData" variant="primary" title="导出 Markdown 报告">
          <Download class="w-4 h-4" /> 报告
        </BaseButton>
      </div>
    </header>

    <!-- Main Grid -->
    <main class="flex-1 overflow-hidden grid grid-cols-1 md:grid-cols-12 gap-0 relative">
      <!-- Left: Suspects (3 cols) -->
      <div 
        class="md:col-span-3 border-r border-mystery-800 bg-mystery-900/50 flex-col h-full md:flex"
        :class="activeTab === 'suspects' ? 'flex' : 'hidden'"
      >
        <div
          class="p-4 border-b border-mystery-800 flex justify-between items-center"
        >
          <h2 class="font-serif text-slate-400">嫌疑人 Dossiers</h2>
          <button
            @click="store.addSuspect()"
            class="text-mystery-gold hover:bg-mystery-gold/10 p-1 rounded transition"
          >
            <Plus class="w-5 h-5" />
          </button>
        </div>
        <div class="flex-1 overflow-y-auto p-4 space-y-3 pb-20 md:pb-4">
          <SuspectCard v-for="s in store.suspects" :key="s.id" :suspect="s" />
        </div>
      </div>

      <!-- Center: Clue Stream (6 cols) -->
      <div
        class="md:col-span-6 flex-col h-full relative bg-slate-900/30 md:flex"
        :class="activeTab === 'timeline' ? 'flex' : 'hidden'"
      >
        <ClueTimeline @preview-image="handlePreviewImage" class="pb-20 md:pb-0" />
      </div>

      <!-- Right: Graph & Analysis (3 cols) -->
      <div
        class="md:col-span-3 border-l border-mystery-800 bg-mystery-900/50 flex-col h-full p-4 md:flex"
        :class="activeTab === 'graph' ? 'flex' : 'hidden'"
      >
        <h2 class="font-serif text-slate-400 mb-4">关联图谱</h2>
        <RelationGraph class="flex-1 mb-4" />

        <div
          class="bg-mystery-800/50 rounded p-4 text-xs text-slate-400 leading-relaxed border border-mystery-700/50 mb-20 md:mb-0"
        >
          <h3 class="font-bold text-mystery-gold mb-2 uppercase tracking-wide">
            侦探笔记
          </h3>
          <p>1. 点击线索旁边的 "+" 可以添加新的发现。</p>
          <p>2. 点击线索卡片中的 @人名 可以快速关联嫌疑人。</p>
          <p>3. 标记为 "凶手" 的嫌疑人会在图谱中显示为红色节点。</p>
        </div>
      </div>
    </main>
    
    <!-- Mobile Bottom Navigation -->
    <nav class="md:hidden fixed bottom-0 left-0 right-0 h-16 bg-mystery-900 border-t border-mystery-800 flex justify-around items-center z-40 text-xs text-slate-500">
        <button class="flex flex-col items-center gap-1 p-2" :class="activeTab === 'suspects' ? 'text-mystery-gold' : ''" @click="activeTab = 'suspects'">
            <Users class="w-5 h-5" />
            <span>嫌疑人</span>
        </button>
        <button class="flex flex-col items-center gap-1 p-2" :class="activeTab === 'timeline' ? 'text-mystery-gold' : ''" @click="activeTab = 'timeline'">
            <div class="relative">
                <FileText class="w-5 h-5" />
                <span v-if="store.clues.length" class="absolute -top-1 -right-1 w-2 h-2 bg-red-500 rounded-full"></span>
            </div>
            <span>线索墙</span>
        </button>
        <button class="flex flex-col items-center gap-1 p-2" :class="activeTab === 'graph' ? 'text-mystery-gold' : ''" @click="activeTab = 'graph'">
            <Share2 class="w-5 h-5" />
            <span>关联图</span>
        </button>
    </nav>

    <!-- Lightbox Modal -->
    <div v-if="previewImage" class="fixed inset-0 z-50 bg-black/90 flex items-center justify-center p-8 backdrop-blur" @click="previewImage = null">
        <img :src="previewImage" class="max-w-full max-h-full rounded shadow-2xl border border-mystery-gold/30" />
        <button class="absolute top-4 right-4 text-white hover:text-mystery-gold">
            <RotateCcw class="w-6 h-6 rotate-45" /> <!-- Using RotateCcw as X icon slightly rotated or just plain text -->
        </button>
    </div>
  </div>
</template>
