<script setup>
import { ref } from "vue";
import { Download, Plus, RotateCcw } from "lucide-vue-next";
import { useCaseStore } from "./stores/useCaseStore";
import SuspectCard from "./components/SuspectCard.vue";
import ClueTimeline from "./components/ClueTimeline.vue";
import RelationGraph from "./components/RelationGraph.vue";
import BaseButton from "./components/ui/BaseButton.vue";

const store = useCaseStore();

const exportData = () => {
  let content = `# ${store.scriptTitle}\n\n`;
  content += `>Generated by Ariadne Clue Organizer\n\n`;

  content += `## 👥 嫌疑人名单\n`;
  store.suspects.forEach((s) => {
    content += `- **${s.name}** ${s.isKiller ? "(🔴凶手)" : ""}: ${
      s.note || "暂无备注"
    }\n`;
  });

  content += `\n## 🕵️‍♂️ 线索流\n`;
  store.clues.forEach((c) => {
    const links = c.linkedSuspectIds
      .map((id) => store.suspects.find((s) => s.id === id)?.name)
      .filter(Boolean)
      .join(", ");
    content += `### ${c.time}\n`;
    content += `- ${c.content}\n`;
    if (links) content += `- 关联: ${links}\n`;
    content += `\n`;
  });

  // Trigger Download
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${store.scriptTitle || "case"}_report.md`;
  a.click();
  URL.revokeObjectURL(url);
};
</script>

<template>
  <div class="min-h-screen bg-black/40 backdrop-blur-3xl flex flex-col">
    <!-- Background Texture -->
    <div
      class="fixed inset-0 pointer-events-none opacity-5 bg-[url('https://www.transparenttextures.com/patterns/dark-matter.png')]"
    ></div>

    <!-- Header -->
    <header
      class="h-16 border-b border-mystery-800 flex items-center justify-between px-6 bg-mystery-900/80 backdrop-blur z-20"
    >
      <div class="flex items-center gap-4">
        <h1 class="text-mystery-gold font-serif text-2xl tracking-wider">
          ARIADNE
        </h1>
        <div class="h-6 w-px bg-mystery-700 mx-2"></div>
        <input
          v-model="store.scriptTitle"
          class="bg-transparent text-xl font-bold text-slate-200 focus:outline-none placeholder-slate-600 font-serif w-64 md:w-96"
          placeholder="在此输入剧本名称..."
        />
      </div>
      <div class="flex items-center gap-3">
        <BaseButton @click="store.resetCase" variant="ghost" class="text-xs">
          <RotateCcw class="w-4 h-4" /> 重置
        </BaseButton>
        <BaseButton @click="exportData" variant="primary">
          <Download class="w-4 h-4" /> 导出档案
        </BaseButton>
      </div>
    </header>

    <!-- Main Grid -->
    <main class="flex-1 overflow-hidden grid grid-cols-1 md:grid-cols-12 gap-0">
      <!-- Left: Suspects (3 cols) -->
      <div
        class="md:col-span-3 border-r border-mystery-800 bg-mystery-900/50 flex flex-col h-[calc(100vh-64px)]"
      >
        <div
          class="p-4 border-b border-mystery-800 flex justify-between items-center"
        >
          <h2 class="font-serif text-slate-400">嫌疑人 Dossiers</h2>
          <button
            @click="store.addSuspect()"
            class="text-mystery-gold hover:bg-mystery-gold/10 p-1 rounded transition"
          >
            <Plus class="w-5 h-5" />
          </button>
        </div>
        <div class="flex-1 overflow-y-auto p-4 space-y-3">
          <SuspectCard v-for="s in store.suspects" :key="s.id" :suspect="s" />
        </div>
      </div>

      <!-- Center: Clue Stream (6 cols) -->
      <div
        class="md:col-span-6 flex flex-col h-[calc(100vh-64px)] relative bg-slate-900/30"
      >
        <ClueTimeline />
      </div>

      <!-- Right: Graph & Analysis (3 cols) -->
      <div
        class="md:col-span-3 border-l border-mystery-800 bg-mystery-900/50 flex flex-col h-[calc(100vh-64px)] p-4"
      >
        <h2 class="font-serif text-slate-400 mb-4">关联图谱</h2>
        <RelationGraph class="flex-1 mb-4" />

        <div
          class="bg-mystery-800/50 rounded p-4 text-xs text-slate-400 leading-relaxed border border-mystery-700/50"
        >
          <h3 class="font-bold text-mystery-gold mb-2 uppercase tracking-wide">
            侦探笔记
          </h3>
          <p>1. 点击线索旁边的 "+" 可以添加新的发现。</p>
          <p>2. 点击线索卡片中的 @人名 可以快速关联嫌疑人。</p>
          <p>3. 标记为 "凶手" 的嫌疑人会在图谱中显示为红色节点。</p>
        </div>
      </div>
    </main>
  </div>
</template>
